name: Backend CI

on:
  push:
    paths:
      - "backend/**"
      - ".github/workflows/backend-ci.yml"
  pull_request:
    paths:
      - "backend/**"
      - ".github/workflows/backend-ci.yml"

concurrency:
  group: backend-ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "21"
          cache: maven

      - name: Make mvnw executable (Linux/Mac)
        working-directory: backend
        run: chmod +x mvnw

      - name: Build with Maven (no tests)
        working-directory: backend
        run: ./mvnw -q -DskipTests package

      # Si más adelante añades tests, cambia a:
      # - name: Build & Test
      #   working-directory: backend
      #   run: ./mvnw -q verify
