name: Frontend CI
on:
  push: { paths: ["frontend/**"] }
  pull_request: { paths: ["frontend/**"] }
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with: { version: 9 }
      - name: Install & Build
        working-directory: frontend
        run: |
          pnpm install --frozen-lockfile
          pnpm build
